import type {
  Achievement,
  Album,
  Giveaway,
  Mission,
  NewsItem,
  Reward,
  Track,
  User,
  UserProfile,
} from '@/types/models';

/**
 * Demo-Datensatz.
 *
 * Alles hier ist Beispielinhalt und wird nur verwendet, solange API und
 * Spotify-Zugangsdaten fehlen. Nichts davon wird je in ein echtes Konto geschrieben,
 * und jeder Bildschirm, der es anzeigt, trägt die Kennzeichnung DEMO-MODUS.
 */

const now = Date.now();
const days = (n: number) => new Date(now + n * 86_400_000).toISOString();

export const DEMO_USER: User = {
  id: 'demo-user',
  email: 'demo@jasonremix.de',
  role: 'USER',
  status: 'ACTIVE',
  createdAt: days(-142),
};

export const DEMO_ADMIN: User = {
  id: 'demo-admin',
  email: 'admin@jasonremix.de',
  role: 'ADMIN',
  status: 'ACTIVE',
  createdAt: days(-400),
};

export const DEMO_PROFILE: UserProfile = {
  userId: 'demo-user',
  username: 'demo_mitglied',
  displayName: 'Demo-Mitglied',
  avatarUrl: null,
  bio: null,
  country: 'DE',
  birthDate: null,
  pushEnabled: false,
  completedAt: days(-140),
};

export const DEMO_STARTING_BALANCE = 45_000;
export const DEMO_STARTING_LIFETIME_EARNED = 52_400;

export const DEMO_TRACKS: Track[] = [
  {
    id: 'trk-zeitgeist',
    title: 'Zeitgeist',
    artist: 'Jason Remix',
    albumId: 'alb-zeitgeist',
    coverUrl: null,
    releaseDate: '2026-07-29',
    genre: 'Electronic',
    durationMs: 214_000,
    isrc: null,
    featured: true,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Zeitgeist',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Zeitgeist',
      appleMusic: 'https://music.apple.com/search?term=Jason%20Remix%20Zeitgeist',
    },
  },
  {
    id: 'trk-havel-nights',
    title: 'Havel Nights',
    artist: 'Jason Remix',
    albumId: 'alb-zeitgeist',
    coverUrl: null,
    releaseDate: '2026-05-15',
    genre: 'Deep House',
    durationMs: 236_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Havel%20Nights',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Havel+Nights',
      appleMusic: 'https://music.apple.com/search?term=Jason%20Remix%20Havel%20Nights',
    },
  },
  {
    id: 'trk-titanium-heart',
    title: 'Titanium Heart',
    artist: 'Jason Remix',
    albumId: 'alb-zeitgeist',
    coverUrl: null,
    releaseDate: '2026-03-06',
    genre: 'Melodic Techno',
    durationMs: 258_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Titanium%20Heart',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Titanium+Heart',
      appleMusic: 'https://music.apple.com/search?term=Jason%20Remix%20Titanium%20Heart',
    },
  },
  {
    id: 'trk-northbound',
    title: 'Northbound',
    artist: 'Jason Remix',
    albumId: 'alb-chrome-season',
    coverUrl: null,
    releaseDate: '2025-11-21',
    genre: 'Progressive House',
    durationMs: 271_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Northbound',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Northbound',
    },
  },
  {
    id: 'trk-chrome-season',
    title: 'Chrome Season',
    artist: 'Jason Remix',
    albumId: 'alb-chrome-season',
    coverUrl: null,
    releaseDate: '2025-09-12',
    genre: 'Electronic',
    durationMs: 199_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Chrome%20Season',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Chrome+Season',
      appleMusic: 'https://music.apple.com/search?term=Jason%20Remix%20Chrome%20Season',
    },
  },
  {
    id: 'trk-obsidian',
    title: 'Obsidian',
    artist: 'Jason Remix',
    albumId: 'alb-chrome-season',
    coverUrl: null,
    releaseDate: '2025-06-27',
    genre: 'Techno',
    durationMs: 288_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Obsidian',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Obsidian',
    },
  },
  {
    id: 'trk-signal-lost',
    title: 'Signal Lost',
    artist: 'Jason Remix',
    albumId: null,
    coverUrl: null,
    releaseDate: '2025-02-14',
    genre: 'Electronic',
    durationMs: 224_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Signal%20Lost',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Signal+Lost',
    },
  },
  {
    id: 'trk-first-light',
    title: 'First Light',
    artist: 'Jason Remix',
    albumId: null,
    coverUrl: null,
    releaseDate: '2024-10-04',
    genre: 'Ambient Electronic',
    durationMs: 312_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20First%20Light',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+First+Light',
    },
  },
];

export const DEMO_ALBUMS: Album[] = [
  {
    id: 'alb-zeitgeist',
    title: 'Zeitgeist',
    artist: 'Jason Remix',
    coverUrl: null,
    releaseDate: '2026-07-29',
    trackIds: ['trk-zeitgeist', 'trk-havel-nights', 'trk-titanium-heart'],
  },
  {
    id: 'alb-chrome-season',
    title: 'Chrome Season',
    artist: 'Jason Remix',
    coverUrl: null,
    releaseDate: '2025-09-12',
    trackIds: ['trk-northbound', 'trk-chrome-season', 'trk-obsidian'],
  },
];

export const DEMO_NEWS: NewsItem[] = [
  {
    id: 'news-zeitgeist',
    category: 'RELEASE',
    title: 'ZEITGEIST ist da',
    body: 'Die neue Single ist auf allen großen Plattformen verfügbar. Hör sie dort, wo du sowieso hörst.',
    imageUrl: null,
    publishedAt: days(-2),
    linkUrl: null,
  },
  {
    id: 'news-tour',
    category: 'TOUR',
    title: 'SEE YOU SOON TOUR 2027',
    body: 'Die Termine in ganz Deutschland stehen. Mitglieder kommen früher an den Ticketvorverkauf.',
    imageUrl: null,
    publishedAt: days(-9),
    linkUrl: null,
  },
  {
    id: 'news-reward',
    category: 'REWARD',
    title: 'Neue Prämie: Sammlerbox',
    body: 'Eine nummerierte Box mit der Chrome-Season-Pressung und einer Mitgliedskarte aus Metall.',
    imageUrl: null,
    publishedAt: days(-16),
    linkUrl: null,
  },
];

export const DEMO_MISSIONS: Mission[] = [
  {
    id: 'msn-daily',
    type: 'DAILY_CHECK_IN',
    title: 'TÄGLICHER BESUCH',
    description: 'Öffne die App einmal am Tag.',
    reward: 100,
    cooldownSeconds: 86_400,
    repeatable: true,
    status: 'AVAILABLE',
    availableAt: null,
    completedAt: null,
    startsAt: null,
    endsAt: null,
  },
  {
    id: 'msn-spotify',
    type: 'CONNECT_SPOTIFY',
    title: 'SPOTIFY VERBINDEN',
    description: 'Verbinde dein Spotify-Konto, damit die App persönlicher wird.',
    reward: 250,
    cooldownSeconds: null,
    repeatable: false,
    status: 'AVAILABLE',
    availableAt: null,
    completedAt: null,
    startsAt: null,
    endsAt: null,
  },
  {
    id: 'msn-profile',
    type: 'COMPLETE_PROFILE',
    title: 'PROFIL VERVOLLSTÄNDIGEN',
    description: 'Wähle einen Benutzernamen und lade ein Bild hoch.',
    reward: 100,
    cooldownSeconds: null,
    repeatable: false,
    status: 'COMPLETED',
    availableAt: null,
    completedAt: days(-140),
    startsAt: null,
    endsAt: null,
  },
  {
    id: 'msn-release',
    type: 'NEW_RELEASE',
    title: 'MISSION ZUR NEUEN SINGLE',
    description: 'Hör ZEITGEIST auf der Plattform deiner Wahl.',
    reward: 250,
    cooldownSeconds: null,
    repeatable: false,
    status: 'AVAILABLE',
    availableAt: null,
    completedAt: null,
    startsAt: days(-2),
    endsAt: days(26),
  },
  {
    id: 'msn-community',
    type: 'COMMUNITY',
    title: 'COMMUNITY-MISSION',
    description: 'Teile die neue Veröffentlichung mit jemandem, der sie noch nicht kennt.',
    reward: 500,
    cooldownSeconds: 604_800,
    repeatable: true,
    status: 'AVAILABLE',
    availableAt: null,
    completedAt: null,
    startsAt: null,
    endsAt: null,
  },
  {
    id: 'msn-event',
    type: 'SPECIAL_EVENT',
    title: 'SONDERAKTION',
    description: 'Woche der Tourankündigung — ein einmaliger Bonus für Mitglieder.',
    reward: 750,
    cooldownSeconds: null,
    repeatable: false,
    status: 'AVAILABLE',
    availableAt: null,
    completedAt: null,
    startsAt: days(-9),
    endsAt: days(12),
  },
];

export const DEMO_REWARDS: Reward[] = [
  {
    id: 'rwd-merch',
    title: 'MERCH',
    subtitle: 'Mitglieder-Shirt, Schwarz auf Schwarz',
    description:
      'Schweres Shirt mit Ton-in-Ton-Aufdruck der Jason-Remix-Marke. Versand innerhalb Deutschlands und der EU.',
    category: 'MERCH',
    cost: 1_000,
    imageUrl: null,
    stock: 200,
    remaining: 146,
    active: true,
    requiresShipping: true,
    minLevel: null,
  },
  {
    id: 'rwd-collector',
    title: 'SAMMLERBOX',
    subtitle: 'Nummerierte Auflage',
    description:
      'Die Chrome-Season-Pressung, eine Mitgliedskarte aus gebürstetem Metall und ein signiertes Einlegeblatt.',
    category: 'COLLECTOR',
    cost: 2_500,
    imageUrl: null,
    stock: 100,
    remaining: 38,
    active: true,
    requiresShipping: true,
    minLevel: 3,
  },
  {
    id: 'rwd-ticket',
    title: 'KONZERTTICKET',
    subtitle: 'See You Soon Tour 2027',
    description: 'Ein Stehplatzticket für einen Termin deiner Wahl, solange verfügbar.',
    category: 'TICKET',
    cost: 5_000,
    imageUrl: null,
    stock: 60,
    remaining: 21,
    active: true,
    requiresShipping: false,
    minLevel: 4,
  },
  {
    id: 'rwd-vip',
    title: 'VIP-ERLEBNIS',
    subtitle: 'Zutritt zum Soundcheck',
    description: 'Früher Einlass, Zutritt zum Soundcheck und ein eigener Mitgliederbereich für den Abend.',
    category: 'EXPERIENCE',
    cost: 10_000,
    imageUrl: null,
    stock: 20,
    remaining: 6,
    active: true,
    requiresShipping: false,
    minLevel: 5,
  },
  {
    id: 'rwd-meet',
    title: 'MEET & GREET',
    subtitle: 'Backstage, vor der Show',
    description: 'Ein Meet & Greet mit Jason in kleiner Runde vor dem Einlass, samt Foto.',
    category: 'EXPERIENCE',
    cost: 15_000,
    imageUrl: null,
    stock: 10,
    remaining: 3,
    active: true,
    requiresShipping: false,
    minLevel: 6,
  },
];

export const DEMO_GIVEAWAYS: Giveaway[] = [
  {
    id: 'gwy-tour-vip',
    title: 'SEE YOU SOON TOUR 2027',
    subtitle: 'VIP-ERLEBNIS',
    description:
      'Zwei VIP-Plätze zum Tourauftakt, inklusive Zutritt zum Soundcheck und Backstage-Bereich.',
    imageUrl: null,
    startsAt: days(-6),
    endsAt: days(18),
    entryCost: 1_000,
    totalEntries: 5_000,
    entriesUsed: 1_842,
    maxEntriesPerUser: 5,
    winnerCount: 2,
    status: 'OPEN',
    terms:
      'Teilnahmeberechtigt sind Mitglieder ab 18 Jahren mit Wohnsitz in der EU. Für Lose eingesetzte Credits werden nach der Ziehung nicht erstattet. Die Gewinner werden per Zufall auf dem Server gezogen und in der App benachrichtigt.',
    myEntries: 0,
    myStatus: null,
  },
  {
    id: 'gwy-studio',
    title: 'STUDIO-SESSION',
    subtitle: 'EIN NACHMITTAG, BRANDENBURG',
    description: 'Verbring einen Nachmittag im Studio, während ein Jason-Remix-Track fertig wird.',
    imageUrl: null,
    startsAt: days(-1),
    endsAt: days(29),
    entryCost: 2_500,
    totalEntries: null,
    entriesUsed: 402,
    maxEntriesPerUser: 2,
    winnerCount: 1,
    status: 'OPEN',
    terms:
      'Teilnahmeberechtigt sind Mitglieder ab 18 Jahren. Die Anreise ist nicht enthalten. Für Lose eingesetzte Credits werden nach der Ziehung nicht erstattet.',
    myEntries: 0,
    myStatus: null,
  },
  {
    id: 'gwy-vinyl',
    title: 'ZEITGEIST-TESTPRESSUNG',
    subtitle: 'EINE VON FÜNF',
    description: 'Eine von fünf signierten Testpressungen aus der Zeitgeist-Session.',
    imageUrl: null,
    startsAt: days(-40),
    endsAt: days(-4),
    entryCost: 500,
    totalEntries: 3_000,
    entriesUsed: 2_988,
    maxEntriesPerUser: 10,
    winnerCount: 5,
    status: 'DRAWN',
    terms: 'Beendet. Die Gewinner wurden gezogen und benachrichtigt.',
    myEntries: 0,
    myStatus: null,
  },
];

export const DEMO_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-listen',
    code: 'FIRST_LISTEN',
    title: 'ERSTES HÖREN',
    description: 'Du hast die App geöffnet und deine Sammlung begonnen.',
    tier: 'STANDARD',
    unlockedAt: days(-142),
    progress: 1,
  },
  {
    id: 'ach-early',
    code: 'EARLY_SUPPORTER',
    title: 'FRÜHER UNTERSTÜTZER',
    description: 'Mitglied seit der ersten Saison.',
    tier: 'RARE',
    unlockedAt: days(-142),
    progress: 1,
  },
  {
    id: 'ach-zeitgeist',
    code: 'ZEITGEIST',
    title: 'ZEITGEIST',
    description: 'Die Mission zur Zeitgeist-Veröffentlichung abgeschlossen.',
    tier: 'STANDARD',
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'ach-super-fan',
    code: 'SUPER_FAN',
    title: 'SUPER FAN',
    description: 'An dreißig verschiedenen Tagen vorbeigeschaut.',
    tier: 'RARE',
    unlockedAt: days(-30),
    progress: 1,
  },
  {
    id: 'ach-collector',
    code: 'CREDITS_COLLECTOR',
    title: 'CREDIT-SAMMLER',
    description: 'Insgesamt 50.000 Credits verdient.',
    tier: 'ELITE',
    unlockedAt: days(-12),
    progress: 1,
  },
  {
    id: 'ach-vip',
    code: 'VIP_MEMBER',
    title: 'VIP-MITGLIED',
    description: 'Level 07 erreicht.',
    tier: 'ELITE',
    unlockedAt: null,
    progress: 0.62,
  },
  {
    id: 'ach-legend',
    code: 'JASON_LEGEND',
    title: 'JASON-LEGENDE',
    description: 'Level 08 erreicht — die höchste Stufe.',
    tier: 'ELITE',
    unlockedAt: null,
    progress: 0.9,
  },
];
