import type {
  Achievement,
  Album,
  Giveaway,
  Mission,
  NewsItem,
  Reward,
  Track,
  User,
  UserProfile,
} from '@/types/models';

/**
 * Demo dataset.
 *
 * Everything here is illustrative placeholder content used only while the API and
 * Spotify credentials are absent. It is never written to a real account, and every
 * screen that renders it shows the DEMO MODE marker.
 */

const now = Date.now();
const days = (n: number) => new Date(now + n * 86_400_000).toISOString();

export const DEMO_USER: User = {
  id: 'demo-user',
  email: 'demo@jasonremix.de',
  role: 'USER',
  status: 'ACTIVE',
  createdAt: days(-142),
};

export const DEMO_ADMIN: User = {
  id: 'demo-admin',
  email: 'admin@jasonremix.de',
  role: 'ADMIN',
  status: 'ACTIVE',
  createdAt: days(-400),
};

export const DEMO_PROFILE: UserProfile = {
  userId: 'demo-user',
  username: 'demo_member',
  displayName: 'Demo Member',
  avatarUrl: null,
  bio: null,
  country: 'DE',
  birthDate: null,
  pushEnabled: false,
  completedAt: days(-140),
};

export const DEMO_STARTING_BALANCE = 45_000;
export const DEMO_STARTING_LIFETIME_EARNED = 52_400;

export const DEMO_TRACKS: Track[] = [
  {
    id: 'trk-zeitgeist',
    title: 'Zeitgeist',
    artist: 'Jason Remix',
    albumId: 'alb-zeitgeist',
    coverUrl: null,
    releaseDate: '2026-07-29',
    genre: 'Electronic',
    durationMs: 214_000,
    isrc: null,
    featured: true,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Zeitgeist',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Zeitgeist',
      appleMusic: 'https://music.apple.com/search?term=Jason%20Remix%20Zeitgeist',
    },
  },
  {
    id: 'trk-havel-nights',
    title: 'Havel Nights',
    artist: 'Jason Remix',
    albumId: 'alb-zeitgeist',
    coverUrl: null,
    releaseDate: '2026-05-15',
    genre: 'Deep House',
    durationMs: 236_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Havel%20Nights',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Havel+Nights',
      appleMusic: 'https://music.apple.com/search?term=Jason%20Remix%20Havel%20Nights',
    },
  },
  {
    id: 'trk-titanium-heart',
    title: 'Titanium Heart',
    artist: 'Jason Remix',
    albumId: 'alb-zeitgeist',
    coverUrl: null,
    releaseDate: '2026-03-06',
    genre: 'Melodic Techno',
    durationMs: 258_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Titanium%20Heart',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Titanium+Heart',
      appleMusic: 'https://music.apple.com/search?term=Jason%20Remix%20Titanium%20Heart',
    },
  },
  {
    id: 'trk-northbound',
    title: 'Northbound',
    artist: 'Jason Remix',
    albumId: 'alb-chrome-season',
    coverUrl: null,
    releaseDate: '2025-11-21',
    genre: 'Progressive House',
    durationMs: 271_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Northbound',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Northbound',
    },
  },
  {
    id: 'trk-chrome-season',
    title: 'Chrome Season',
    artist: 'Jason Remix',
    albumId: 'alb-chrome-season',
    coverUrl: null,
    releaseDate: '2025-09-12',
    genre: 'Electronic',
    durationMs: 199_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Chrome%20Season',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Chrome+Season',
      appleMusic: 'https://music.apple.com/search?term=Jason%20Remix%20Chrome%20Season',
    },
  },
  {
    id: 'trk-obsidian',
    title: 'Obsidian',
    artist: 'Jason Remix',
    albumId: 'alb-chrome-season',
    coverUrl: null,
    releaseDate: '2025-06-27',
    genre: 'Techno',
    durationMs: 288_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Obsidian',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Obsidian',
    },
  },
  {
    id: 'trk-signal-lost',
    title: 'Signal Lost',
    artist: 'Jason Remix',
    albumId: null,
    coverUrl: null,
    releaseDate: '2025-02-14',
    genre: 'Electronic',
    durationMs: 224_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20Signal%20Lost',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+Signal+Lost',
    },
  },
  {
    id: 'trk-first-light',
    title: 'First Light',
    artist: 'Jason Remix',
    albumId: null,
    coverUrl: null,
    releaseDate: '2024-10-04',
    genre: 'Ambient Electronic',
    durationMs: 312_000,
    isrc: null,
    featured: false,
    links: {
      spotify: 'https://open.spotify.com/search/Jason%20Remix%20First%20Light',
      youtube: 'https://www.youtube.com/results?search_query=Jason+Remix+First+Light',
    },
  },
];

export const DEMO_ALBUMS: Album[] = [
  {
    id: 'alb-zeitgeist',
    title: 'Zeitgeist',
    artist: 'Jason Remix',
    coverUrl: null,
    releaseDate: '2026-07-29',
    trackIds: ['trk-zeitgeist', 'trk-havel-nights', 'trk-titanium-heart'],
  },
  {
    id: 'alb-chrome-season',
    title: 'Chrome Season',
    artist: 'Jason Remix',
    coverUrl: null,
    releaseDate: '2025-09-12',
    trackIds: ['trk-northbound', 'trk-chrome-season', 'trk-obsidian'],
  },
];

export const DEMO_NEWS: NewsItem[] = [
  {
    id: 'news-zeitgeist',
    category: 'RELEASE',
    title: 'ZEITGEIST is out now',
    body: 'The new single is available on every major platform. Stream it wherever you listen.',
    imageUrl: null,
    publishedAt: days(-2),
    linkUrl: null,
  },
  {
    id: 'news-tour',
    category: 'TOUR',
    title: 'SEE YOU SOON TOUR 2027',
    body: 'Dates across Germany announced. Members get early access to the ticket window.',
    imageUrl: null,
    publishedAt: days(-9),
    linkUrl: null,
  },
  {
    id: 'news-reward',
    category: 'REWARD',
    title: 'New reward: Collector Box',
    body: 'A numbered box with the Chrome Season pressing and a metal member card.',
    imageUrl: null,
    publishedAt: days(-16),
    linkUrl: null,
  },
];

export const DEMO_MISSIONS: Mission[] = [
  {
    id: 'msn-daily',
    type: 'DAILY_CHECK_IN',
    title: 'DAILY CHECK-IN',
    description: 'Open the app once a day.',
    reward: 100,
    cooldownSeconds: 86_400,
    repeatable: true,
    status: 'AVAILABLE',
    availableAt: null,
    completedAt: null,
    startsAt: null,
    endsAt: null,
  },
  {
    id: 'msn-spotify',
    type: 'CONNECT_SPOTIFY',
    title: 'CONNECT SPOTIFY',
    description: 'Link your Spotify account to personalise your experience.',
    reward: 250,
    cooldownSeconds: null,
    repeatable: false,
    status: 'AVAILABLE',
    availableAt: null,
    completedAt: null,
    startsAt: null,
    endsAt: null,
  },
  {
    id: 'msn-profile',
    type: 'COMPLETE_PROFILE',
    title: 'COMPLETE PROFILE',
    description: 'Choose a username and add a picture.',
    reward: 100,
    cooldownSeconds: null,
    repeatable: false,
    status: 'COMPLETED',
    availableAt: null,
    completedAt: days(-140),
    startsAt: null,
    endsAt: null,
  },
  {
    id: 'msn-release',
    type: 'NEW_RELEASE',
    title: 'NEW RELEASE MISSION',
    description: 'Listen to ZEITGEIST on your platform of choice.',
    reward: 250,
    cooldownSeconds: null,
    repeatable: false,
    status: 'AVAILABLE',
    availableAt: null,
    completedAt: null,
    startsAt: days(-2),
    endsAt: days(26),
  },
  {
    id: 'msn-community',
    type: 'COMMUNITY',
    title: 'COMMUNITY MISSION',
    description: 'Share the new release with someone who has not heard it yet.',
    reward: 500,
    cooldownSeconds: 604_800,
    repeatable: true,
    status: 'AVAILABLE',
    availableAt: null,
    completedAt: null,
    startsAt: null,
    endsAt: null,
  },
  {
    id: 'msn-event',
    type: 'SPECIAL_EVENT',
    title: 'SPECIAL EVENT',
    description: 'Tour announcement week — a one-off bonus for members.',
    reward: 750,
    cooldownSeconds: null,
    repeatable: false,
    status: 'AVAILABLE',
    availableAt: null,
    completedAt: null,
    startsAt: days(-9),
    endsAt: days(12),
  },
];

export const DEMO_REWARDS: Reward[] = [
  {
    id: 'rwd-merch',
    title: 'MERCH',
    subtitle: 'Member tee, black on black',
    description:
      'Heavyweight tee with a tonal Jason Remix mark. Ships within Germany and the EU.',
    category: 'MERCH',
    cost: 1_000,
    imageUrl: null,
    stock: 200,
    remaining: 146,
    active: true,
    requiresShipping: true,
    minLevel: null,
  },
  {
    id: 'rwd-collector',
    title: 'COLLECTOR BOX',
    subtitle: 'Numbered edition',
    description:
      'The Chrome Season pressing, a brushed metal member card and a signed insert.',
    category: 'COLLECTOR',
    cost: 2_500,
    imageUrl: null,
    stock: 100,
    remaining: 38,
    active: true,
    requiresShipping: true,
    minLevel: 3,
  },
  {
    id: 'rwd-ticket',
    title: 'CONCERT TICKET',
    subtitle: 'See You Soon Tour 2027',
    description: 'One standing ticket for a date of your choice, subject to availability.',
    category: 'TICKET',
    cost: 5_000,
    imageUrl: null,
    stock: 60,
    remaining: 21,
    active: true,
    requiresShipping: false,
    minLevel: 4,
  },
  {
    id: 'rwd-vip',
    title: 'VIP EXPERIENCE',
    subtitle: 'Soundcheck access',
    description: 'Early entry, soundcheck access and a dedicated member area for the night.',
    category: 'EXPERIENCE',
    cost: 10_000,
    imageUrl: null,
    stock: 20,
    remaining: 6,
    active: true,
    requiresShipping: false,
    minLevel: 5,
  },
  {
    id: 'rwd-meet',
    title: 'MEET & GREET',
    subtitle: 'Backstage, before the show',
    description: 'A small-group meet & greet with Jason before doors, plus a photo.',
    category: 'EXPERIENCE',
    cost: 15_000,
    imageUrl: null,
    stock: 10,
    remaining: 3,
    active: true,
    requiresShipping: false,
    minLevel: 6,
  },
];

export const DEMO_GIVEAWAYS: Giveaway[] = [
  {
    id: 'gwy-tour-vip',
    title: 'SEE YOU SOON TOUR 2027',
    subtitle: 'VIP EXPERIENCE',
    description:
      'Two VIP places for the tour opening, including soundcheck access and backstage entry.',
    imageUrl: null,
    startsAt: days(-6),
    endsAt: days(18),
    entryCost: 1_000,
    totalEntries: 5_000,
    entriesUsed: 1_842,
    maxEntriesPerUser: 5,
    winnerCount: 2,
    status: 'OPEN',
    terms:
      'Open to members aged 18 or over resident in the EU. Credits spent on entries are not refundable once the draw has taken place. Winners are drawn at random on the server and notified in the app.',
    myEntries: 0,
    myStatus: null,
  },
  {
    id: 'gwy-studio',
    title: 'STUDIO SESSION',
    subtitle: 'ONE AFTERNOON, BRANDENBURG',
    description: 'Spend an afternoon in the studio while a Jason Remix track is finished.',
    imageUrl: null,
    startsAt: days(-1),
    endsAt: days(29),
    entryCost: 2_500,
    totalEntries: null,
    entriesUsed: 402,
    maxEntriesPerUser: 2,
    winnerCount: 1,
    status: 'OPEN',
    terms:
      'Open to members aged 18 or over. Travel is not included. Credits spent on entries are not refundable once the draw has taken place.',
    myEntries: 0,
    myStatus: null,
  },
  {
    id: 'gwy-vinyl',
    title: 'ZEITGEIST TEST PRESSING',
    subtitle: 'ONE OF FIVE',
    description: 'One of five signed test pressings from the Zeitgeist session.',
    imageUrl: null,
    startsAt: days(-40),
    endsAt: days(-4),
    entryCost: 500,
    totalEntries: 3_000,
    entriesUsed: 2_988,
    maxEntriesPerUser: 10,
    winnerCount: 5,
    status: 'DRAWN',
    terms: 'Closed. Winners have been drawn and notified.',
    myEntries: 0,
    myStatus: null,
  },
];

export const DEMO_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-listen',
    code: 'FIRST_LISTEN',
    title: 'FIRST LISTEN',
    description: 'You opened the app and started your collection.',
    tier: 'STANDARD',
    unlockedAt: days(-142),
    progress: 1,
  },
  {
    id: 'ach-early',
    code: 'EARLY_SUPPORTER',
    title: 'EARLY SUPPORTER',
    description: 'A member since the first season.',
    tier: 'RARE',
    unlockedAt: days(-142),
    progress: 1,
  },
  {
    id: 'ach-zeitgeist',
    code: 'ZEITGEIST',
    title: 'ZEITGEIST',
    description: 'Completed the Zeitgeist release mission.',
    tier: 'STANDARD',
    unlockedAt: null,
    progress: 0,
  },
  {
    id: 'ach-super-fan',
    code: 'SUPER_FAN',
    title: 'SUPER FAN',
    description: 'Checked in on thirty separate days.',
    tier: 'RARE',
    unlockedAt: days(-30),
    progress: 1,
  },
  {
    id: 'ach-collector',
    code: 'CREDITS_COLLECTOR',
    title: 'CREDITS COLLECTOR',
    description: 'Earned 50,000 credits in total.',
    tier: 'ELITE',
    unlockedAt: days(-12),
    progress: 1,
  },
  {
    id: 'ach-vip',
    code: 'VIP_MEMBER',
    title: 'VIP MEMBER',
    description: 'Reached level 07.',
    tier: 'ELITE',
    unlockedAt: null,
    progress: 0.62,
  },
  {
    id: 'ach-legend',
    code: 'JASON_LEGEND',
    title: 'JASON LEGEND',
    description: 'Reached level 08 — the highest tier.',
    tier: 'ELITE',
    unlockedAt: null,
    progress: 0.9,
  },
];
